### ISSUE TITLE
Où est ma chaine de Markov

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/courses#3]
@Tom-Bonnike?

**Comment by Tom-Bonnike** [comment]
Je finis ça bientôt https://github.com/tom-bonnike/workshop-hetic. <sub><sub><sub>MAIS JE NE PROMETS RIEN ¯\\_(ツ)_/¯ </sub></sub></sub>

**Comment by Tom-Bonnike** [comment]
https://github.com/Tom-Bonnike/workshop-hetic/commit/ac0934889e8533cbb662428a53ce69039ef08cc2

Le résultat est pas ouf mais bon 🐸

**Comment by Yomguithereal** [comment]
J'ai ouvert une review toute moche sur ton repo.
