### ISSUE TITLE
[Ortho] Bref historique

### ISSUE THREAD

**Issue by charlespv** [Yomguithereal/courses#9]
> Les fondements théoriques de l’Open data sont anciens.
> 
> Article XV de la DDHC (seul à être aménagé dans la _consitution_ **constitution**, sigh).
> 
> "La Société a le droit de demander compte à tout Agent public de son administration."
> 
> Ce droit n’est pas appliqué en totalité en France aujourd’hui.
> 
> ===

**Comment by Yomguithereal** [comment]
Fixed :)
